### ISSUE TITLE
"Failed to compile."

### ISSUE THREAD

**Issue by mikestopcontinues** [miguelmota/is-valid-domain#25]
With the latest version, my NextJS build (using Webpack 5) fails. Here's the error:

```
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'punycode' in '/Users/msc/Code/@sitearcade/words/node_modules/is-valid-domain'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "punycode": require.resolve("punycode/") }'
	- install 'punycode'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "punycode": false }


> Build error occurred
Error: > Build failed because of webpack errors
    at /PROJECT/node_modules/next/dist/build/index.js:15:924
    at async Span.traceAsyncFn (/PROJECT/node_modules/next/dist/telemetry/trace/trace.js:6:584)
```

**Comment by miguelmota** [comment]
@mikestopcontinues sorry about this! can you try the release recently published? thanks

**Comment by mikestopcontinues** [comment]
Works like a charm! Thanks!
